#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-joineR
Version  : 1.2.4
Release  : 11
URL      : https://cran.r-project.org/src/contrib/joineR_1.2.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/joineR_1.2.4.tar.gz
Summary  : Joint Modelling of Repeated Measurements and Time-to-Event Data
Group    : Development/Tools
License  : GPL-3.0
Requires: R-rlang
BuildRequires : R-markdown
BuildRequires : R-rlang
BuildRequires : R-statmod
BuildRequires : buildreq-R

%description
# joineR <img src="man/figures/hex.png" width = "175" height = "200" align="right" />

%prep
%setup -q -c -n joineR

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552957820

%install
export SOURCE_DATE_EPOCH=1552957820
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library joineR
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library joineR
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library joineR
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  joineR || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/joineR/CITATION
/usr/lib64/R/library/joineR/DESCRIPTION
/usr/lib64/R/library/joineR/INDEX
/usr/lib64/R/library/joineR/LICENSE
/usr/lib64/R/library/joineR/Meta/Rd.rds
/usr/lib64/R/library/joineR/Meta/data.rds
/usr/lib64/R/library/joineR/Meta/features.rds
/usr/lib64/R/library/joineR/Meta/hsearch.rds
/usr/lib64/R/library/joineR/Meta/links.rds
/usr/lib64/R/library/joineR/Meta/nsInfo.rds
/usr/lib64/R/library/joineR/Meta/package.rds
/usr/lib64/R/library/joineR/Meta/vignette.rds
/usr/lib64/R/library/joineR/NAMESPACE
/usr/lib64/R/library/joineR/NEWS.md
/usr/lib64/R/library/joineR/R/joineR
/usr/lib64/R/library/joineR/R/joineR.rdb
/usr/lib64/R/library/joineR/R/joineR.rdx
/usr/lib64/R/library/joineR/data/Rdata.rdb
/usr/lib64/R/library/joineR/data/Rdata.rds
/usr/lib64/R/library/joineR/data/Rdata.rdx
/usr/lib64/R/library/joineR/doc/competing-risks.R
/usr/lib64/R/library/joineR/doc/competing-risks.Rmd
/usr/lib64/R/library/joineR/doc/competing-risks.html
/usr/lib64/R/library/joineR/doc/index.html
/usr/lib64/R/library/joineR/doc/joineR.R
/usr/lib64/R/library/joineR/doc/joineR.Rmd
/usr/lib64/R/library/joineR/doc/joineR.html
/usr/lib64/R/library/joineR/help/AnIndex
/usr/lib64/R/library/joineR/help/aliases.rds
/usr/lib64/R/library/joineR/help/figures/hex.png
/usr/lib64/R/library/joineR/help/joineR.rdb
/usr/lib64/R/library/joineR/help/joineR.rdx
/usr/lib64/R/library/joineR/help/paths.rds
/usr/lib64/R/library/joineR/html/00Index.html
/usr/lib64/R/library/joineR/html/R.css
/usr/lib64/R/library/joineR/tests/testthat.R
/usr/lib64/R/library/joineR/tests/testthat/Rplots.pdf
/usr/lib64/R/library/joineR/tests/testthat/test-ancillary.R
/usr/lib64/R/library/joineR/tests/testthat/test-comprisk.R
/usr/lib64/R/library/joineR/tests/testthat/test-misc.R
/usr/lib64/R/library/joineR/tests/testthat/test-models.R
/usr/lib64/R/library/joineR/tests/testthat/test-plot.R
